"""empty message

Revision ID: 48b8b0ec30f2
Revises: ecc27c395564
Create Date: 2021-11-24 11:02:07.535920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b8b0ec30f2'
down_revision = 'ecc27c395564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pangolin_result', 'pangolearn_version',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_comment='Pangolearn version',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pangolin_result', 'pangolearn_version',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_comment='Pangolearn version',
               existing_nullable=True)
    # ### end Alembic commands ###
