"""empty message

Revision ID: 5e11ccbd47f3
Revises: 860aee337f99
Create Date: 2022-12-23 15:30:56.366481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e11ccbd47f3'
down_revision = '860aee337f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('culture_identifier', sa.VARCHAR(length=30), nullable=True, comment='An identifier to differentiate multiple cultures from the same sample on the same day. It will usually be 1, but if this is the second culture done on this sample on this day, it needs to be 2 (and so on).'),
    sa.Column('date_cultured', sa.DateTime(), nullable=True, comment='Date this culture was done'),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('extraction', sa.Column('culture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'extraction', 'culture', ['culture_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extraction', type_='foreignkey')
    op.drop_column('extraction', 'culture_id')
    op.drop_table('culture')
    # ### end Alembic commands ###
