"""empty message

Revision ID: c48cdec0b1db
Revises: 3c0306c7e377
Create Date: 2021-07-24 12:09:58.056410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48cdec0b1db'
down_revision = '3c0306c7e377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiling_pcr', sa.Column('protocol', sa.VARCHAR(length=60), nullable=True, comment='Tiling PCR protocol'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiling_pcr', 'protocol')
    # ### end Alembic commands ###
